# Generated by Django 3.0.3 on 2021-05-09 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 27, 18, 857835, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='view',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 15, 27, 18, 857433, tzinfo=utc), editable=False),
        ),
    ]
