# Generated by Django 3.0.3 on 2021-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210509_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
